project:
  type: website
  output-dir: docs

website:
  title: "A Quarto Website"
  navbar:
    left:
      - href: Assignment 2.qmd
        text: Assignment 2

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
